### PR TITLE
More from the inbox.

### PR DESCRIPTION
**Pull request by timabell**

### CODE REVIEW

**Comment by alexmbird** [comment]
Not sure Capita belong in here - they offer far more services than IT recruitment and blocking the domain may not be what most people want. 

Can you do another request with just the other two?

**Comment by timabell** [comment]
I'll do ask you ask, though if they want to send emails like the below then as far as I'm concerned they'll get all their mail filtered ;-)

> -------- Forwarded Message --------
> Subject: 	12-18 month contract - reading
> Date: 	Thu, 22 Jan 2015 10:10:56 +0000
> From: 	Whillock, Mike (Capita Resourcing & Development) <Mike.Whillock@capita.co.uk>
> To: 	tim@timwise.co.uk
> 
> Hi Tim,
> 
> I hope you are well.
> 
> Just picked up your CV on the job boards.
> 
> I have a reading based digital agency offering a 6 month rolling contract c# MVC.
> 
> Give me a call ASAP.
> 
> Best,

**Comment by alexmbird** [comment]
Ugh.  Can't say I blame you.  Trouble is, a lot of people are likely to be working alongside Capita and it would hurt if all mails from capita.co.uk ended up in the bin.  We could list all of their recruiters one by one but that's inelegant.  I wonder if a better solution could be found.

**Comment by timabell** [comment]
Oh I don't know, having had first-hand dealings with crapita, it wouldn't do the world any harm if all their mail ended up in the bin, lol.

When I have to deal with a recruiter (I'm a contractor so it's a regular thing for me) I use a shell script https://gist.github.com/timabell/2cc21c21957a45fa7df8 to update my sieve script, and put the relevant company's name in the `SKIP` variable, which means they go into inbox for the duration of my dealings with them. It also combines the recruiter filter with my other custom sieve filters.

Inverted grep is a handy thing :-)

**Pull request closed without merging**
