### PR TITLE
Added cv-library.co.uk

### PR DESCRIPTION
**Pull request by pwuk**

### CODE REVIEW

**Comment by alexmbird** [comment]
Unless I'm missing something I don't think cv-library.co.uk is actually a recruitment agency?

**Comment by pwuk** [comment]
Maybe, my resoning is I get job listing emails from them and their site allows me to search jobs by location.
I suppose it's not really differenty from jobserve et al

**Comment by alexmbird** [comment]
I think it's important to keep this list to companies that are acting as recruitment consultants/agents - a lot of people will want to filter those out but not regular alerts from job listing sites.  I'll remove it from `domains.txt`.

**Comment by pwuk** [comment]
fair do's

**Pull request merged**
