### PR TITLE
Adding more uk domains

### PR DESCRIPTION
**Pull request by claudio-viola**
Some more domains.. will add more! Thanks!

### CODE REVIEW

**Comment by alexmbird** [comment]
Hi Claudio,

126 new domains!  Thanks for this.  

I've taken a look at a handful.  Most are recruitment agencies, but a few (e.g. accionlabs.com, suntradingllc.com) look like ordinary employers.  I'd hate for the wong companies to end up on the list so would you mind checking everything in the PR is definitely a recruitment agency?

Cheers,
Alex

**Comment by claudio-viola** [comment]
yeah those two are not! Will remove them. have you found anything else?
I started adding a few and then i could not stop  it may have gone out of hands.... but in the meantime my account is now super clean! thanks!

**Comment by alexmbird** [comment]
I haven't had the time to check all 126 of them, but if you can weed out any that aren't recruitment agencies I'll be happy to accept a revised PR.

**Comment by claudio-viola** [comment]
removed accionlabs.com, suntradingllc.com and cognizant! couldnt find anything else

**Comment by alexmbird** [comment]
Awesome, thanks.  Merged!

**Pull request merged**
