### PR TITLE
Add dice.com

### PR DESCRIPTION
**Pull request by robinbowes**

### CODE REVIEW

**Comment by alexmbird** [comment]
Usually I try to check out domains to make sure they really are a recruiter.  Having read Dice's "About Us" page (which links to a company with a different name) I have absolutely no idea what they do.  Well done Dice, whoever you are.

Added.

**Comment by robinbowes** [comment]
http://uk.dice.com/

http://uk.dice.com/includes/ITJB4/Themes/uk/images/logo.png

**Comment by alexmbird** [comment]
I see.  This list is solely for recruitment agencies - not job boards.  A few people block emails based upon this list and adding dice.com would end up dropping legitimate messages.

**Comment by robinbowes** [comment]
Ah, well you might want to remove that last PR then :)

Or maybe consider a two-tier list - one for general recruitment-related domains, and one for spammy recruiters that need blocking?

R.

**Comment by alexmbird** [comment]
Good idea, I'm up for separate lists.  Maybe people the ruleset generator scripts could have a, `--I-don't-want-a-new-job-at-all` flag to include job site domains as well.

**Pull request merged**
